# Generated by Django 5.0.6 on 2024-05-22 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
