# Generated by Django 5.0.6 on 2024-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
