# Generated by Django 5.0.6 on 2024-05-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
